#undef HT_PREFIX
#undef SLOT_VALUE_TYPE
#undef SLOT_KEY_TYPE
#undef SLOT_TYPE
#undef TABLE_COUNTERS
#undef COUNT_TOMBS
#undef SLOTS_BUFFER
#undef HASH_TABLE_SIZE
#undef KEY_HASH_FUNC
#undef KEY_COMP_FUNC
#undef VALUE_INIT_FUNC
// #undef INIT_SLOT_CALLBACK
