#version 460
layout(local_size_x = 256) in;


layout(set = 0, binding = 0) uniform UniformBufferObject {
    uint image_width;
    uint image_height;
    uint num_layers;
} ubo;

layout(set = 0, binding = 1) uniform sampler2D uEquirectangularMap;
layout(set = 0, binding = 2, rgba32f) uniform writeonly imageCube outEnvMap;

const float PI = 3.14159265358979323846;

vec3 cubemap_texel_to_direction(uint id_x, uint id_y, uint id_face, uint face_size)
{
    // map texel center to [-1, 1]
    float a = 2.0 * ((float(id_x) + 0.5) / float(face_size)) - 1.0;
    float b = 2.0 * ((float(id_y) + 0.5) / float(face_size)) - 1.0;

    vec3 dir;

    if (id_face == 0u) {         // +X
        dir = vec3( 1.0, -b, -a );
    } else if (id_face == 1u) {  // -X
        dir = vec3( -1.0, -b,  a );
    } else if (id_face == 2u) {  // +Y
        dir = vec3(  a,  1.0,  b );
    } else if (id_face == 3u) {  // -Y
        dir = vec3(  a, -1.0, -b );
    } else if (id_face == 4u) {  // +Z
        dir = vec3(  a, -b,  1.0 );
    } else {                     // -Z
        dir = vec3( -a, -b, -1.0 );
    }

    return normalize(dir);
}

vec2 direction_to_equirect_uv(vec3 dir) {
    dir = normalize(dir);

    float u = atan(dir.z, dir.x) / (2.0 * PI) + 0.5;
    float v = asin(clamp(dir.y, -1.0, 1.0)) / PI + 0.5;

    return vec2(u, v);
}

void main() {
    uint x_id = gl_GlobalInvocationID.x;
    uint y_id = gl_GlobalInvocationID.y;
    uint z_id = gl_GlobalInvocationID.z;
    
    if (x_id >= ubo.image_width) return;
    if (y_id >= ubo.image_height) return;
    if (z_id >= ubo.num_layers) return;

    vec3 dir = cubemap_texel_to_direction(x_id, y_id, uint(z_id), uint(ubo.image_width));
    vec2 uv = direction_to_equirect_uv(dir);
    
    vec4 out_color = vec4(texture(uEquirectangularMap, uv).xyz, 1.0f);
    imageStore(outEnvMap, ivec3(x_id, y_id, z_id), out_color);


    // imageStore(outEnvMap, ivec3(x_id, y_id, z_id), vec4(1.0, 0.0, 0.0, 1.0));
}